-- Operational definitions from the reviewed CFAC files.
-- Governance metadata only: no workbook rows, no names, no client/case data.

insert into metric_definitions
  (key, display_name, definition, category, program_area, unit, calc_rule, owner, source_note, sort_order)
values
  ('maintenance_requests_total', 'Maintenance Requests',
   'Count of maintenance requests submitted through the Maintenance Request Form.',
   'operational', 'operations', 'count',
   'One count per form row, grouped by the request month.',
   'Operations', 'Maintenance Request Form 2026 aggregate-derived import.', 610),
  ('maintenance_requests_by_type', 'Maintenance Requests by Type',
   'Maintenance request count grouped by request type.',
   'operational', 'operations', 'count',
   'COUNT(requests) GROUP BY request_type and month. Names, emails, locations, and narratives are not stored.',
   'Operations', 'Maintenance Request Form 2026 aggregate-derived import.', 611),
  ('maintenance_requests_by_priority', 'Maintenance Requests by Priority',
   'Maintenance request count grouped by priority.',
   'operational', 'operations', 'count',
   'COUNT(requests) GROUP BY priority and month.',
   'Operations', 'Maintenance Request Form 2026 aggregate-derived import.', 612),
  ('maintenance_requests_by_status', 'Maintenance Requests by Status',
   'Maintenance request count grouped by status.',
   'operational', 'operations', 'count',
   'COUNT(requests) GROUP BY status and month.',
   'Operations', 'Maintenance Request Form 2026 aggregate-derived import.', 613),
  ('maintenance_on_time_yes', 'Maintenance Completed On Time',
   'Count of maintenance requests marked completed on time.',
   'operational', 'operations', 'count',
   'COUNT(requests) where On Time? = Yes, grouped by month.',
   'Operations', 'Maintenance Request Form 2026 aggregate-derived import.', 614),
  ('maintenance_actual_cost', 'Maintenance Actual Cost',
   'Total actual maintenance cost reported in the maintenance log.',
   'operational', 'operations', 'usd',
   'SUM(actual_cost) grouped by month.',
   'Operations', 'Maintenance Request Form 2026 aggregate-derived import.', 615),
  ('fleet_trips_total', 'Fleet Trips',
   'Count of vehicle-use log entries.',
   'operational', 'operations', 'count',
   'One count per fleet form row, grouped by vehicle-use month.',
   'Operations', 'Fleet Management 2026 aggregate-derived import.', 620),
  ('fleet_trips_by_vehicle_type', 'Fleet Trips by Vehicle Type',
   'Fleet trip count grouped by vehicle type.',
   'operational', 'operations', 'count',
   'COUNT(trips) GROUP BY vehicle_type and month. Driver names, locations, and narratives are not stored.',
   'Operations', 'Fleet Management 2026 aggregate-derived import.', 621),
  ('fleet_trips_by_purpose', 'Fleet Trips by Purpose',
   'Fleet trip count grouped by broad travel purpose.',
   'operational', 'operations', 'count',
   'COUNT(trips) GROUP BY purpose and month. Purpose is treated as client-adjacent and used only as an aggregate bucket.',
   'Operations', 'Fleet Management 2026 aggregate-derived import.', 622),
  ('fleet_miles_driven', 'Fleet Miles Driven',
   'Total miles driven from fleet log entries.',
   'operational', 'operations', 'count',
   'SUM(miles_driven) grouped by month.',
   'Operations', 'Fleet Management 2026 aggregate-derived import.', 623),
  ('fleet_low_fuel_returns', 'Fleet Low-Fuel Returns',
   'Count of fleet trips returned with less than a half tank of fuel.',
   'operational', 'operations', 'count',
   'COUNT(trips) where 1/2 Tank of Fuel? = No, grouped by month.',
   'Operations', 'Fleet Management 2026 aggregate-derived import.', 624),
  ('fleet_maintenance_issue_reports', 'Fleet Maintenance Issue Reports',
   'Count of fleet log entries that reported a maintenance issue.',
   'operational', 'operations', 'count',
   'COUNT(trips) where a maintenance issue narrative was present. The narrative itself is not stored.',
   'Operations', 'Fleet Management 2026 aggregate-derived import.', 625)
on conflict (key) do update set
  display_name = excluded.display_name,
  definition = excluded.definition,
  category = excluded.category,
  program_area = excluded.program_area,
  unit = excluded.unit,
  calc_rule = excluded.calc_rule,
  owner = excluded.owner,
  source_note = excluded.source_note,
  sort_order = excluded.sort_order,
  updated_at = now();
